### ISSUE TITLE
The templates should have at least one simple route and controller, like 'Hello World'.

### ISSUE THREAD

**Issue by mchamoudadev** [sharafdin/yonode#345]
### Feature Summary

Mongoose should have at least one simple route and controller, like 'Hello World'.

### Detailed Solution

Mongoose should have at least one simple route and controller, like 'Hello World'.

### Compliance Checklist

- [X] I have checked for similar feature requests and found none.
- [X] I have explained the feature with enough detail for it to be understood.
- [X] I have provided a clear rationale for why this feature should be implemented.

**Comment by Omar-Tood** [comment]
JS-MongoDB-Prisma-NoAuth-Template already taken

**Comment by isasharafdin** [comment]
Js-PostgreSql-Prisma-noAuth For @abdinasir-Tman and he completed

**Comment by Omar-Tood** [comment]
JS-MySQL-Prisma-NoAuth-Template already taken @Omar-Tood

**Comment by Omar-Tood** [comment]
JS-PostgreSQL-Sequelize-NoAuth-Template already teken by @Omar-Tood

**Comment by Omar-Tood** [comment]
JS-MongoDB-TypeORM-NoAuth-Template already taken by @Omar-Tood

**Comment by Omar-Tood** [comment]
JS-MySQL-TypeORM-NoAuth-Template already taken by @Omar-Tood

**Comment by miirshe** [comment]
JS-MySQL-Prisma-NoAuth-Template already taken by @miirshe

**Comment by miirshe** [comment]
JS-MySQL-Sequelize-NoAuth-Template already taken by @miirshe

**Comment by miirshe** [comment]
JS-PostgreSQL-TypeORM-Auth-Template already taken by @miirshe

**Comment by miirshe** [comment]
JS-PostgreSQL-TypeORM-NoAuth-Template already taken by @miirshe

**Comment by isasharafdin** [comment]
completed this issues with @abdinasir-Tman , @Omar-Tood & @miirshe . thanks engineers for your effort.

**Comment by Omar-Tood** [comment]
> completed this issues with @abdinasir-Tman , @Omar-Tood & @miirshe . thanks engineers for your effort.

Thanks engr Sharafdin
