### ISSUE TITLE
Prisma package must be in devDependencies not in Dependencies .

### ISSUE THREAD

**Issue by isasharafdin** [sharafdin/yonode#460]
### Yonode Version

v1.2.3

### Link to the code or a minimal reproduction

https://www.npmjs.com/package/yonode?activeTab=versions

### Steps to Reproduce

.

### Checklist

- [X] I have filled in all the required fields.
- [X] I have searched for existing issues to avoid duplicates.
- [X] This is a bug report specific to Yonode and not general Node.js or Express.js issues.

**Comment by Argus416** [comment]
fixed in this pull request

**Comment by isasharafdin** [comment]
> fixed in this pull request #463

you fix one of 4 bro. there is 3 left. look all of the prisma templates and you will find them. @Argus416

**Comment by Argus416** [comment]
There is only 2 left https://github.com/sharafdin/yonode/pull/464

**Comment by isasharafdin** [comment]
> There is only 2 left #464

yeh i saw it . thanks
